services:
  eureka-server:
    build: .
    image: taohans/gestaocerta:eureka-server
    container_name: eureka-server
    environment:
      - SERVER_PORT=8761
    ports:
      - "8761:8761"
    networks:
      - gestaocerta-private

networks:
  gestaocerta-private:
    external: true